version: '3'

services:
    mcl:
        image: openjdk:11
        container_name: mcl
        restart: always
        volumes:
            - '/path/to/mcl:/mcl'
        working_dir: /mcl
        entrypoint: sh ./mcl.sh
        expose:
            - 8088
    mongo:
        image: mongo
        restart: always
        volumes:
            - '/path/to/mongo/data:/data/db'
            - '/path/to/mongo/mongod.conf:/etc/mongo/mongod.conf'
        expose:
            - 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: <password>
        command: --config /etc/mongo/mongod.conf
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #     - 8089:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: <password>
    #         ME_CONFIG_MONGODB_URL: mongodb://root:<password>@mongo:27017/
    ransoim:
        build: /path/to/ransoim/.
        restart: always
        volumes:
            - '/path/to/ransoim:/ransoim'
        environment:
            - TZ=Asia/Shanghai
        depends_on:
            - mcl
            - mongo
        

        